# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: f.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'f.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x07\x66.proto\x12\x08\x65xchange\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\"(\n\tTimeFrame\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x91\x01\n\rTradesRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05since\x18\x02 \x01(\x03\x12)\n\x0bmarket_type\x18\x03 \x01(\x0e\x32\x14.exchange.MarketType\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\'\n\x06params\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"-\n\x0eTradesResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x8d\x01\n\x0cOhlcvRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12&\n\ttimeframe\x18\x02 \x01(\x0b\x32\x13.exchange.TimeFrame\x12\r\n\x05since\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\'\n\x06params\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\",\n\rOhlcvResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x83\x01\n\x0eTickersRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05since\x18\x02 \x01(\x03\x12)\n\x0bmarket_type\x18\x03 \x01(\x0e\x32\x14.exchange.MarketType\x12\'\n\x06params\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\".\n\x0fTickersResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t*.\n\nMarketType\x12\n\n\x06\x46UTURE\x10\x00\x12\x08\n\x04SPOT\x10\x01\x12\n\n\x06OPTION\x10\x02\x32\xcd\x01\n\x0b\x45xchangeApi\x12>\n\tGetTrades\x12\x17.exchange.TradesRequest\x1a\x18.exchange.TradesResponse\x12;\n\x08GetOhlcv\x12\x16.exchange.OhlcvRequest\x1a\x17.exchange.OhlcvResponse\x12\x41\n\nGetTickers\x12\x18.exchange.TickersRequest\x1a\x19.exchange.TickersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'f_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETTYPE']._serialized_start=687
  _globals['_MARKETTYPE']._serialized_end=733
  _globals['_TIMEFRAME']._serialized_start=78
  _globals['_TIMEFRAME']._serialized_end=118
  _globals['_TRADESREQUEST']._serialized_start=121
  _globals['_TRADESREQUEST']._serialized_end=266
  _globals['_TRADESRESPONSE']._serialized_start=268
  _globals['_TRADESRESPONSE']._serialized_end=313
  _globals['_OHLCVREQUEST']._serialized_start=316
  _globals['_OHLCVREQUEST']._serialized_end=457
  _globals['_OHLCVRESPONSE']._serialized_start=459
  _globals['_OHLCVRESPONSE']._serialized_end=503
  _globals['_TICKERSREQUEST']._serialized_start=506
  _globals['_TICKERSREQUEST']._serialized_end=637
  _globals['_TICKERSRESPONSE']._serialized_start=639
  _globals['_TICKERSRESPONSE']._serialized_end=685
  _globals['_EXCHANGEAPI']._serialized_start=736
  _globals['_EXCHANGEAPI']._serialized_end=941
# @@protoc_insertion_point(module_scope)
