# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: methodid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'methodid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emethodid.proto\x12\tfetchdata\x1a\x1cgoogle/protobuf/struct.proto\"q\n\x0cInvokeMethod\x12\x30\n\tmethod_id\x18\x01 \x01(\x0e\x32\x13.fetchdata.MethodIDR\x08methodId\x12/\n\x06params\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\x06params*\xe9\x01\n\x08MethodID\x12\r\n\tUNDEFINED\x10\x00\x12\x0c\n\x08\x45XCHANGE\x10\x01\x12\n\n\x06MARKET\x10\x02\x12\x11\n\rUPDATE_MARKET\x10\x03\x12\t\n\x05OHLCV\x10\n\x12\x0c\n\x08UN_OHLCV\x10\x0b\x12\r\n\tORDERBOOK\x10\x14\x12\x0b\n\x07TICKERS\x10\x1e\x12\n\n\x06TRADES\x10(\x12\r\n\tUN_TRADES\x10)\x12\x11\n\rHISTORY_OHLCV\x10\x37\x12\x15\n\x11HISTORY_ORDERBOOK\x10\x38\x12\x13\n\x0fHISTORY_TICKERS\x10\x39\x12\x12\n\x0eHISTORY_TRADES\x10:Bb\n\rcom.fetchdataB\rMethodidProtoP\x01\xa2\x02\x03\x46XX\xaa\x02\tFetchdata\xca\x02\tFetchdata\xe2\x02\x15\x46\x65tchdata\\GPBMetadata\xea\x02\tFetchdatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'methodid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.fetchdataB\rMethodidProtoP\001\242\002\003FXX\252\002\tFetchdata\312\002\tFetchdata\342\002\025Fetchdata\\GPBMetadata\352\002\tFetchdata'
  _globals['_METHODID']._serialized_start=175
  _globals['_METHODID']._serialized_end=408
  _globals['_INVOKEMETHOD']._serialized_start=59
  _globals['_INVOKEMETHOD']._serialized_end=172
# @@protoc_insertion_point(module_scope)
